"""The generalisation result: the same policy on tracks nobody looked at (feature 011).

**Reads two committed evaluation CSVs and computes everything else**, so the report reproduces from
a clean clone with no traces and no dataset (FR-010). The policy is an input to this feature, never
an output: nothing here trains, tunes or selects a checkpoint.

**Every rate is reported with a Wilson interval and never alone.** Both sets sit at 100 per cent,
and the normal approximation would report `[1.00, 1.00]` for each, which claims certainty from a
few dozen runs and would make the two look identically perfect rather than differently uncertain.
Ten perfect runs are consistent with a policy that fails one track in four; thirty-three are not.
That difference is the entire value of having run this, and it is invisible without the interval.

Usage::

    python -m python.rl.generalisation

Runs under ``.venv``.
"""

from __future__ import annotations

import argparse
import hashlib
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from python.eda.intervals import ProportionInterval, wilson

HELD_OUT_CSV = Path("results") / "rl" / "eval_ppo_car_009_bc_deterministic.csv"
GENERALISATION_CSV = Path("results") / "rl" / "eval_ppo_car_009_bc_generalisation_deterministic.csv"
MODEL = Path("unity") / "SelfDrivingSim" / "Assets" / "Models" / "ppo_car_009_bc-5000101.onnx"

#: What one run has to do to count. Three laps, not one, so SC-002 is measured three times stricter
#: than M3 asked for. Recorded here because a completion rate means nothing without it.
LAPS_PER_RUN = 3


@dataclass(frozen=True)
class SetResult:
    """One seed set's outcome, with the interval it is only meaningful inside."""

    name: str
    frame: pd.DataFrame
    interval: ProportionInterval

    @property
    def completed(self) -> int:
        return self.interval.successes

    @property
    def runs(self) -> int:
        return self.interval.trials

    @property
    def wall_contacts(self) -> int:
        return int(self.frame["wall_contacts"].sum())

    @property
    def end_reasons(self) -> dict[str, int]:
        return self.frame["end_reason"].value_counts().to_dict()

    @property
    def controllers(self) -> list[str]:
        return sorted(self.frame["controller"].astype(str).unique())

    def lap_times(self) -> pd.Series:
        done = self.frame["completed_lap"].astype(str).str.lower().isin(("true", "1"))
        return self.frame.loc[done, "lap_time_s"]


def load(path: Path, name: str) -> SetResult:
    frame = pd.read_csv(path)
    done = frame["completed_lap"].astype(str).str.lower().isin(("true", "1"))

    if frame["seed"].duplicated().any():
        raise ValueError(f"{path} runs a seed twice, so the rate would double count (SC-002)")

    return SetResult(
        name=name,
        frame=frame,
        interval=wilson(int(done.sum()), len(frame), scope=name),
    )


def model_fingerprint(path: Path) -> str:
    """SC-003. A claim that two sweeps used the same policy is checkable or it is an assertion."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verdict(generalisation: SetResult, held_out: SetResult) -> tuple[str, str]:
    """Which of research R7's four pre-registered readings applies.

    **Chosen by the numbers rather than by preference**, which is the whole reason R7 was written
    before the sweep ran. The branches are in the order R7 lists them.
    """
    if generalisation.completed == generalisation.runs:
        return (
            "case 1, every run completed",
            "The policy drives this distribution of tracks, not only the ten it was reported on. "
            "M3's recorded limit closes.",
        )

    if generalisation.interval.overlaps(held_out.interval):
        return (
            "case 2, intervals overlap",
            "No difference detected at this sample size. Not evidence that generalisation failed, "
            "and not evidence that it holds.",
        )

    return (
        "case 3, intervals disjoint",
        "A real generalisation gap. The held-out ten were easier or luckier than the generator's "
        "typical output. M3's verdict is not edited: it was closed on the evidence it named, and "
        "this is a limit recorded beside it.",
    )


def to_markdown(generalisation: SetResult, held_out: SetResult, fingerprint: str) -> str:
    case, reading = verdict(generalisation, held_out)
    lines: list[str] = []
    add = lines.append

    add("# Generalisation: the same policy on tracks nobody looked at")
    add("")
    add("Generated by `python -m python.rl.generalisation` from two committed evaluation CSVs.")
    add("No training, no tuning, no checkpoint selection. The policy is an input to this report.")
    add("")
    add("## The policy, identified rather than asserted")
    add("")
    add(f"- file: `{MODEL.as_posix()}`")
    add(f"- sha256: `{fingerprint}`")
    add("- byte identical to the trainer's own output at `results/ppo_car_009_bc/CarDriver/`")
    add(f"- controller column, derived at runtime: {', '.join(f'`{c}`' for c in generalisation.controllers)}")
    add("")
    add("The controller column is built from the model asset actually loaded and the inference mode")
    add("actually in effect, so these rows prove what drove them. It used to be a hand-typed string")
    add("whose own tooltip said nothing checked it, and the scene was in fact holding a different")
    add("seed's model with deterministic inference off when this feature started.")
    add("")

    add("## Result")
    add("")
    add(f"| | held out (seeds 1001-1010) | **generalisation (seeds 2001-2040)** |")
    add("|---|---|---|")
    add(f"| runs | {held_out.runs} | **{generalisation.runs}** |")
    add(f"| laps per run | {LAPS_PER_RUN} | {LAPS_PER_RUN} |")
    add(f"| completed | {held_out.completed} | **{generalisation.completed}** |")
    add(f"| rate | {100 * held_out.interval.point:.1f}% | **{100 * generalisation.interval.point:.1f}%** |")
    add(f"| **Wilson 95%** | [{100 * held_out.interval.low:.1f}, {100 * held_out.interval.high:.1f}] "
        f"| **[{100 * generalisation.interval.low:.1f}, {100 * generalisation.interval.high:.1f}]** |")
    add(f"| wall contacts | {held_out.wall_contacts} | **{generalisation.wall_contacts}** |")
    lap = generalisation.lap_times()
    hlap = held_out.lap_times()
    add(f"| lap time, mean | {hlap.mean():.3f} s | {lap.mean():.3f} s |")
    add(f"| lap time, sd | {hlap.std():.3f} s | {lap.std():.3f} s |")
    add("")
    add(f"**End reasons, generalisation set**: {generalisation.end_reasons}.")
    add("")
    add("Read the end reasons rather than only the rate: a wall contact, a time limit and a")
    add("no-progress stall are three different findings and averaging them into `did not finish`")
    add("would discard the one that matters.")
    add("")

    add("## Verdict against the pre-registered reading")
    add("")
    add(f"**Research R7, {case}.** {reading}")
    add("")
    add("**The intervals are the point.** Both sets read 100 per cent, and a bare percentage would")
    add("say they are the same result. They are not: ten perfect runs are consistent with a policy")
    add(f"that fails one track in four ([{100 * held_out.interval.low:.1f}, "
        f"{100 * held_out.interval.high:.1f}]), while thirty-three are not "
        f"([{100 * generalisation.interval.low:.1f}, {100 * generalisation.interval.high:.1f}]). ")
    add("What this sweep bought is a narrower bound, not a higher number.")
    add("")

    add("## What this cannot say")
    add("")
    add("- **The new tracks come from the same generator under the same acceptance bound**, so the")
    add("  claim is about a distribution of tracks rather than about track design in general. A")
    add("  different generator, a different topology or a real road is a larger question.")
    add("- **They are slightly easier, not harder**, and that was measured before the sweep rather")
    add("  than discovered after: pooled peak steering demand 0.695 against training's 0.789 and")
    add("  held-out's 0.738. So this is not a claim that the policy handles harder tracks.")
    add("- **It says nothing new about M3.** M3 was closed on the evidence it named. This is a")
    add("  measurement recorded beside that verdict, and it would have been recorded the same way")
    add("  if it had come out badly.")
    add("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)

    held_out = load(args.root / HELD_OUT_CSV, "held out")
    generalisation = load(args.root / GENERALISATION_CSV, "generalisation")
    fingerprint = model_fingerprint(args.root / MODEL)

    case, reading = verdict(generalisation, held_out)
    print(f"held out       {held_out.interval}")
    print(f"generalisation {generalisation.interval}")
    print(f"overlap        {generalisation.interval.overlaps(held_out.interval)}")
    print(f"wall contacts  {generalisation.wall_contacts}")
    print(f"end reasons    {generalisation.end_reasons}")
    print(f"verdict        R7 {case}")
    print(f"               {reading}")

    out = args.out or args.root / "results" / "rl" / "generalisation.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(to_markdown(generalisation, held_out, fingerprint), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
